#!/bin/sh

# Add a boot loader entry after the freedesktop.org Boot Loader Specification

export version="$(basename -- "${1}")"
exec envsubst < entry.conf.sh > "/boot/loader/entries/${version}.conf"
